### ISSUE TITLE
Any plans to support Open API spec v3.0?

### ISSUE THREAD

**Issue by dilipkrish** [hgwood/fanfaron#5]

**Comment by hgwood** [comment]
Hello! I'm afraid not. Two reasons: 

- As far as I've seen (that is not much), Open API 3 is quite a bit different and it might warrant a new lib. Am I mistaken? If you have opinions on this I'd like to hear it.
- I don't work quite as close as APIs anymore so I don't have time to devote to write this new lib or evolve Fanfaron further.

If you write your own lib or fork Fanfaron and make additions, ping me and I'll advertise the project on the Fanfaron readme.

**Comment by dilipkrish** [comment]
Don't have the bandwidth myself to work on it. Just that I had this library bookmarked since it was a clean(er) implementation of the swagger object model for use with [springfox](http://springfox.io). Will take a look and see how much effort it is to port it to v3.0. Curious, whats does _fanfaron_ mean?

**Comment by hgwood** [comment]
It's the literal French translation of the word *swagger*.
